### ISSUE TITLE
Nová sekce "Fórum"

### ISSUE THREAD

**Issue by burningtree** [gweicz/web#1]
Mezi první tmavou část a část s Projekty umístit výpis nejžhavějších vláken z našeho Fóra za poslední týden (dejme tomu posledních 5). Možná by tam mohl být i nějaký přepínač týden, měsíc, rok.. nevím, to už není tak podstatné.

Jsou dvě možnosti jak to udělat:
a) možná má Discourse nějaký plugin, který umožní udělat widget ala Twitter
b) vytáhnout to z API a vyrenderovat custom u nás 

<img width="757" alt="Screenshot 2021-03-09 at 23 45 07" src="https://user-images.githubusercontent.com/67269/110542347-39e6c780-8129-11eb-8ad6-9d7691acff05.png">

**Comment by rixcian** [comment]
To jsme zrovna probírali v pondělí na Web Devs Call #4.

Já měl stejný nápad. Napojit tu aktuální sekci "Novinky v komunitě" na Discourse API a brát z ní ale např. jenom příspěvky s určitým tagem, např. "gweicz-web" s tím, že by ho mohli používat jenom členové Councilu.. 

Nicméně jsem zjistil, že omezit použití tagu pro určitou skupinu nejde (nebo alespoň jsem na to nepřišel).
