### ISSUE TITLE
CzechPunks

### ISSUE THREAD

**Issue by generalbytes** [gweicz/web#10]
Ahoj,
Web CzechPunks nese stejný rukopis jako web gwei.cz, Myslím si, že je potřeba opravit níže uvedenou textaci na stránkách 
"Jak konkrétně CzechPunks pomáhají?
"20 % etherů zaplacených za mint je automaticky odesíláno na donate adresu české Ethereové komunity Gwei.cz"
... Autoři projektu CzechPunks nejsou s žádným z podporovaných subjektů nijak spojeni."

**Comment by burningtree** [comment]
Zdravím, doporučuji obrátit se přímo na CzechPunks.

Já nevím, kdo zatím stojí - Gwei.cz s tím opravdu nemá nic společného - informace o CzechPunks se v naší komunitě objevili až po oznámení.

BTW, co je myšleno tím, že web gwei.cz nese stejný rukopis?
